### PR TITLE
Re-Translation for docs of EF Core Managing-Schemas for better smooth reading

### PR DESCRIPTION
**Pull request by personball**
I want to **Re-Tranlate** docs of [/ef/core/managing-schemas/migrations/](https://docs.microsoft.com/zh-cn/ef/core/managing-schemas/migrations/) in **Simplified Chinese(zh-CN)**，make it better for smooth reading.

### CODE REVIEW

**Comment by v-elcou** [comment]
Hello, @personball, 
Thank for your contribution. We are currently reviewing and will communicate the decision taken. 
Thanks for your time and support on this.

Kind regards,
Microsoft C&E Localization Team

**Comment by personball** [comment]
All files under ef core /managing-schemas/ updated.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by LisandroSu** [comment]
Hello, @personball 

Thank you for your feedback and suggestion. 
 
The feedback has been partially accepted.. We will adjust  your feedback in order to comply with Microsoft Style Guide. We will release this article in the next localization release round accordingly.

Many thanks for your time and  support on this. 
 
Microsoft C&E Localization Team

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by personball** [comment]
Hi @LisandroSu 
Is @olprod  a robot?

**Pull request merged**
